### ISSUE TITLE
3y Terms in us-east-2 (Ohio) not supported

### ISSUE THREAD

**Issue by mariahct** [awslabs/amazon-dynamodb-tools#13]
Currently the script defaults to 1y terms for us-east-2, however 3y RIs are available to purchase in this region (see image), and this is a common region with DDB use among our customers.  Please add these as supported recos by the script.

Image is of console with 3y RI purchase available in Ohio:

![DDB RI 3y terms available in Ohio](https://user-images.githubusercontent.com/125480426/219068019-cc4ba16b-a16d-4dc3-a3cb-c3f756ba56eb.JPG)

**Comment by switch180** [comment]
3 year reservations [are not available in Ohio](https://aws.amazon.com/dynamodb/pricing/provisioned/).

Would you be willing to create an issue/feedback for the new AWS calculator with feedback on this problem?

**Comment by switch180** [comment]
I see the issue now - we do offer them on the APIs and in the console.

>   {
            "DurationSeconds": 94608000,
            "RecurringCharges": {
                "RecurringChargesFrequency": "Hourly",
                "RecurringChargesAmount": 8.1e-05
            },
            "SubscriptionFee": 1.8,
            "UsageType": "WriteCapacityUnit-Hrs"
        },
        {
            "DurationSeconds": 94608000,
            "RecurringCharges": {
                "RecurringChargesFrequency": "Hourly",
                "RecurringChargesAmount": 1.6e-05
            },
            "SubscriptionFee": 0.36,
            "UsageType": "ReadCapacityUnit-Hrs"
        }


I will update the pricing config with this data.

**Comment by switch180** [comment]
More regions?!

### CA Central 1
>{
            "DurationSeconds": 94608000,
            "RecurringCharges": {
                "RecurringChargesFrequency": "Hourly",
                "RecurringChargesAmount": 1.8e-05
            },
            "SubscriptionFee": 0.396,
            "UsageType": "ReadCapacityUnit-Hrs"
        },
        {
            "DurationSeconds": 94608000,
            "RecurringCharges": {
                "RecurringChargesFrequency": "Hourly",
                "RecurringChargesAmount": 9e-05
            },
            "SubscriptionFee": 1.98,
            "UsageType": "WriteCapacityUnit-Hrs"
        }

### EU West 2

 {
            "DurationSeconds": 94608000,
            "RecurringCharges": {
                "RecurringChargesFrequency": "Hourly",
                "RecurringChargesAmount": 9.7e-05
            },
            "SubscriptionFee": 2.1357,
            "UsageType": "WriteCapacityUnit-Hrs"
        },
        {
            "DurationSeconds": 94608000,
            "RecurringCharges": {
                "RecurringChargesFrequency": "Hourly",
                "RecurringChargesAmount": 1.9e-05
            },
            "SubscriptionFee": 0.4272,
            "UsageType": "ReadCapacityUnit-Hrs"
        }

**Comment by switch180** [comment]
Released in the latest version. Get it here: https://github.com/awslabs/amazon-dynamodb-tools/releases/latest
