### ISSUE TITLE
Boto3 is required but not listed in requirements.txt

### ISSUE THREAD

**Issue by Kyle-sandeman-mrdfood** [awslabs/amazon-dynamodb-tools#18]
Steps to reproduce
1. Clone repo and `cd`
2. `python -m venv venv` and `source venv/bin/activate`
3. `pip install -r requirements.txt`
4. `python table_class_evaluator.py`

Result:
```
Traceback (most recent call last):
  File "table_class_evaluator.py", line 8, in <module>
    import boto3
ModuleNotFoundError: No module named 'boto3'
```

**Comment by tebanieo** [comment]
Added the required functionality, closing the Issue, Thanks for reporting it!
