### ISSUE TITLE
DynamoDB reco tool not excluding Infrequent Access usage for calculations

### ISSUE THREAD

**Issue by gcalv0** [awslabs/amazon-dynamodb-tools#9]
DynamoDB reco tool not excluding Infrequent Access usage for calculations

DynamoDB reserved capacity recommendations tool should be excluding the usage of Standard Infrequent Access tables, as these are not included in the reservations scope.

As confirmed by AWS team, this case is not considered and was suggested to raise the issue.

Version used: 1.0.0

**Comment by switch180** [comment]
Can you provide some sanitized billing data with Standard-IA storage in it so we can see what you see?

**Comment by switch180** [comment]
In addition, could you ask the AWS representative you mentioned to send details of this issue to dynamodb-sa@amazon.com? This email address is only open to Amazon senders. Or, send them a link to this issue and have them reach out to me.

**Comment by arjanschaaf** [comment]
@switch180 Adding some sanitized CUR data with both Standard (eu-west-1) and Standard-IA (eu-central-1) data on both Read & Write consumption.

[sanitized_cur_data.csv](https://github.com/awslabs/amazon-dynamodb-tools/files/10177860/sanitized_cur_data.csv)

**Comment by switch180** [comment]
@gcalv0  @arjanschaaf would either of you be able to checkout the code in https://github.com/awslabs/amazon-dynamodb-tools/pull/10 and verify that the patch excludes your S-IA units? The new regex passes the unit and integration tests, which are strong evidence that the code now filters out S-IA usage in its calculations.

**Comment by switch180** [comment]
Fixed and released. See [#reco-v1.1.0](https://github.com/awslabs/amazon-dynamodb-tools/releases/tag/reco-v1.1.0)
